###extensión Rest Client instalada para poder Probar peticiones


### GET PAGINA DE INICIO
GET http://localhost:3000

### GET TODOS LOS POSTEOS EN EL MENU EDICION
GET http://localhost:3000/posteo


### GET POSTEO POR ID
GET http://localhost:3000/posteo/29


### POST CREAR UN POSTEO
POST http://localhost:3000/posteo
Content-Type: application/json

{
    "titulo":"Almanza",
    "contenido":"Todo por dos pesos"
}


### PUT (Editar un posteo)    
PUT http://localhost:3000/posteo/99
Content-Type: application/json

{
    "titulo":"Kuanip",
    "contenido":"Barrio loco"
}

### DELETE
DELETE http://localhost:3000/posteo/46